config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  root to: "pages#landing"

  # get 'generate_days', to: 'days#generate_days', as: :generate_days
  resources :days, only: [:create, :index, :show, :update] do
    resources :tasks, only: [:create]
  end

  resources :tasks, only: [:update, :destroy]

  resources :categories, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :color, allow_nil: true, format: { with: /#([0-9a-f]{6}|[0-9a-f]{3})/i }
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_one_attached :highlight

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :highlight, :day_date ],
  associated_against: {
    tasks: [ :description ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :day
  belongs_to :category, optional: true

  validates :description, presence: true
  # validates :priority, presence: true, numericality: { only_integer: true, in: (1..3) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :days, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :tasks, through: :days

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = Category.new( name: category_params[:name] )
    @category.user = current_user
    unless @category.save!
      flash[:alert] = "Error creating category"
    end

    respond_to do |format|
      format.text { render partial: 'days/category', locals: { category: @category, task_id: params[:task_id] }, formats: :html}
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
  end

  def delete
    @category = Category.find(params[:id])
    @category.destroy
  end

  private

  def category_params
    params.require(:category).permit(:name, :day, :color)
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  def create
    all_days = current_user.days
    if current_user.days.empty?
      Day.create!(user_id: current_user.id, created_at: Date.today, day_date: Date.today.strftime("%A %e %B %Y"))
    end
    last_day = DateTime.parse(all_days.last.created_at.to_s)

    missing_days = (DateTime.now - last_day).to_i
    missing_days.times do |i|
      Day.create!(user_id: current_user.id, created_at: Date.today - missing_days + i + 1, day_date: (Date.today - missing_days + i + 1).strftime("%A %e %B %Y"))
    end

    respond_to do |format|
      format.text { render plain: current_user.days.last.id.to_s }
    end
  end

  def index
    @days = current_user.days.order(created_at: :desc)
    if params[:query].present?
      @days = Day.global_search(params[:query])
    else
      @days = current_user.days.order(created_at: :desc)
    end
  end

  def show
    @categories = Category.all
    @day = Day.find(params[:id])
    @task = Task.new
    @tasks = @day.tasks.order(priority: :asc)
    @category = Category.new
  end

  def update
    @day = Day.find(params[:id])
    @day.update(day_params)
  end

  private

  def day_params
    params.require(:day).permit(:highlight, :name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing]

  def landing
    @day = Day.last
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.new(task_params)
    day = Day.find(params[:day_id])
    @task.day = day
    unless @task.save!
      flash[:alert] = @task.errors.full_messages
    end

    respond_to do |format|
      format.html { redirect_to day_path(day) }
      format.text { render partial: 'days/task', locals: { task: @task, categories: Category.all, day: day }, formats: :html}
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:description, :priority, :category_id, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/days/_category.html.erb
<div class="category-btn-and-color-popup"
           data-controller="category-color"
           data-category-color-category-id-value=<%= category.id %>
           data-action="mouseover->category-color#showColorPopup mouseout->category-color#hideColorPopup">
    <form action=<%="/tasks/#{task_id}"%> method="patch">
        <button type="submit" class="category-btn" name=task[category_id] value=<%= category.id %>
                style="color: <%= category.color if category.color.present? %>"
                data-category-color-target="categoryName"
                data-action="click->task-update#updateCategoryBoxColor">
                <%= category.name %></button>
        <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
    </form>

    <div class="category-color-popup btn-hidden"
            data-category-color-target="colorSelectorPopup">
        <i class="fa-solid fa-palette category-color-btn"></i>
        <input type="color" name="category[color]" class="category-color-picker"
                data-category-color-target="colorPickerInput"
                data-action="change->category-color#submitColorChange">
    </div>
</div>

app/views/days/_task.html.erb
<div class="task"
      data-controller="task-update"
      data-task-update-task-id-value=<%= task.id %>
      data-task-update-task-priority-value=<%= task.priority %>
      data-action="mouseover->task-update#showPopups mouseout->task-update#hidePopups">

  <div class="categories-menu hidden"
       data-task-update-target="categoriesPopup"
       data-controller="category-create"
       data-action="click@window->task-update#hideCategoriesPopup"
       data-category-create-task-id-value=<%=task.id%>>

    <% categories.reverse_each do |category| %>
      <%= render partial: "days/category", locals: { category: category, task_id: task.id} %>
    <% end %>

    <form action=<%="/tasks/#{task.id}"%> method="patch">
      <button type="submit" class="category-btn" name=task[category_id] data-action="click->task-update#clearCategory">- clear category</button>
      <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
    </form>

    <form action="/categories" method="post" data-action="submit->category-create#newCategory">
      <input type="text" placeholder="+ new category" name="category[name]" data-category-create-target="categoryNameInputField">
      <input type="hidden" name="day" value="<%=day.id%>">
      <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
    </form>

  </div>

  <form action=<%="/tasks/#{task.id}"%> method="patch">
    <div class="category" style="background-color: <%= task.category.color if task.category.present? && task.category.color.present? %>"
         data-action="click->task-update#toggleCategoriesPopup"
         data-task-update-target="categoryBox">
      <%= task.category.name.first unless task.category.nil? %>
    </div>

    <input type="text" name="task[description]" value="<%=task.description%>">

    <button type="submit" name="task[completed]" class="checkmark <%= 'done' if task.completed? %>" value=<%= !task.completed? %>
            data-task-update-target="checkmark"
            data-action="click->task-update#completeTask">
      <% if task.completed? %>
        <i class="fa-solid fa-check"></i>
      <% end %>

    </button>

    <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
  </form>

  <i class="fa-solid fa-circle-xmark delete-btn btn-hidden"
      data-task-update-target="deleteButton"
      data-action="click->task-update#deleteTask"></i>

  <div class="update-priority-button">

    <i class="fa-solid fa-circle-exclamation btn-hidden"
       data-task-update-target="priorityButton"
       data-action="click->task-update#showPrioritySelector"></i>

    <div class="priority-options hidden"
         data-task-update-target="prioritySelector">
      <p data-action="click->task-update#updatePriority">1</p>
      <p data-action="click->task-update#updatePriority">2</p>
      <p data-action="click->task-update#updatePriority">3</p>
    </div>

  </div>
</div>

app/views/days/index.html.erb
<div class="navbar"
     data-controller="hotdog-navigation"
     data-hotdog-navigation-logged-in-value=<%= user_signed_in? %>
     data-login-navigation-logged-in-value=<%= user_signed_in? %>
     data-action="click@window->hotdog-navigation#hideMenu">

    <div id="hotdog-menu"
         data-hotdog-navigation-target="threeBars"
         data-action="click->hotdog-navigation#toggleMenu">
      <div class="bar-top"></div>
      <div class="bar-long"></div>
      <div class="bar-bottom"></div>
    </div>

    <a href="/days/<%= Day.last.id %>" class="option-1 hidden" data-hotdog-navigation-target="option1">today</a>
    <a href="/" class="option-2 hidden" data-hotdog-navigation-target="option2">home</a>


    <div class="bg-circles">
      <div class="one progress" data-hotdog-navigation-target="circle1"></div>
      <div class="two progress" data-hotdog-navigation-target="circle2"></div>
      <div class="three progress" data-hotdog-navigation-target="circle3"></div>
      <div class="four progress" data-hotdog-navigation-target="circle4"></div>
    </div>

  <div class="search-bar">
    <%= form_with url: days_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search for tasks or dates"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>

</div>


<div class="progress-container">
  <div class="days-container">
    <div class="cards">

      <% @days.each do |day| %>

        <% if day.highlight.present? %>
          <div class="progress-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path day.highlight.key, height: 300, crop: :fill %>')">
        <% else %>
          <div class ="progress-card" style="background-color: #81EBE0;">
        <% end %>

            <div class="progress-content">
              <% display_date = Date.parse(day.created_at.to_s)%>
              <% formatted_date = display_date.strftime('%e %B') %>
             <h2 class="progress-title"> <%= formatted_date %></h2>
              <p class="progress-copy"><%= day.name %> </p>
              <%= link_to "View Day", day_path(day), class: "progress-btn" %>
            </div>

          </div>
      <% end %>
    </div>

  </div>
</div>
  <h1 id="progress">progress.</h1>
</div>

app/views/days/show.html.erb
<div class="navbar"
     data-controller="hotdog-navigation"
     data-hotdog-navigation-logged-in-value=<%= user_signed_in? %>
     data-action="click@window->hotdog-navigation#hideMenu">

  <div id="hotdog-menu"
       data-hotdog-navigation-target="threeBars"
       data-action="click->hotdog-navigation#toggleMenu">
    <div class="bar-top"></div>
    <div class="bar-long"></div>
    <div class="bar-bottom"></div>
  </div>

  <a href="/days" class="option-1 hidden" data-hotdog-navigation-target="option1">progress</a>
  <a href="/" class="option-2 hidden" data-hotdog-navigation-target="option2">home</a>

  <div class="bg-circles bg-circles-today">
    <div class="one today" data-hotdog-navigation-target="circle1"></div>
    <div class="two today" data-hotdog-navigation-target="circle2"></div>
    <div class="three today" data-hotdog-navigation-target="circle3"></div>
    <div class="four today" data-hotdog-navigation-target="circle4"></div>
  </div>

</div>

<div class="today-page-container">

  <div class="highlight-and-date-container">
    <div></div>

    <div class="highlight" style="<%= %Q(background-image: url(#{cl_image_path @day.highlight.key}); border: none;) if @day.highlight.present?%>"
         data-controller="highlight">
      <p><i class="fa-regular fa-image"></i><br>click to add a photo highlight for today!</p>
      <form enctype="multipart/form-data" action=<%="/days/#{@day.id}"%> method="post" data-highlight-target="highlightForm">
        <input type="file" name="day[highlight]" id="highlightUpload" data-action="change->highlight#uploadHighlight">
        <input type="hidden" name="_method" value="patch">
        <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
      </form>
    </div>

    <div class="day-name-and-date" data-controller="reduce-text-size edit">
      <form action=<%="/days/#{@day.id}"%> method="patch">
        <input id="name-input" type="text" name="day[name]" value="<%= @day.name.nil? ? "today." : @day.name %>"
              data-reduce-text-size-target="input"
              data-edit-target="dayNameInput"
              data-action="keyup->reduce-text-size#reduceTextSize">
        <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
      </form>

      <h2><%= (@day.created_at).strftime('%e %B %Y') %></h2>
    </div>

  </div>

  <div class="tasks-and-new-container"
       data-controller="task-create"
       data-task-create-day-id-value=<%=@day.id%>>
    <div class="new-task-container">
      <form data-action="submit->task-create#createTask">
        <input type="text" placeholder="type here to add a new task" class="new-task-input" data-task-create-target="inputField">
      </form>
    </div>

    <div class="tasks-container" data-task-create-target="tasksContainer">
      <% @tasks.each do |task| %>
        <%= render partial: "task", locals: { task: task, categories: @categories, day: @day} %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <%= favicon_link_tag %>

    <% if controller_name == "days" && action_name == "show" %>
    <title>focus. | today</title>
    <% elsif controller_name == "days" && action_name == "index" %>
    <title>focus. | progress</title>
    <% else %>
    <title>focus. | manage your day</title>
    <% end %>

    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>

</html>

app/views/pages/landing.html.erb
<div class="navbar"
     data-controller="login-navigation hotdog-navigation days-generation"
     data-hotdog-navigation-logged-in-value=<%= user_signed_in? %>
     data-action="click@window->login-navigation#closeAll click@window->hotdog-navigation#hideMenu">

  <div id="hotdog-menu"
        data-login-navigation-target="threeBars"
        data-hotdog-navigation-target="threeBars"
        data-action="click->login-navigation#toggleMenu click->hotdog-navigation#toggleMenu">
      <div id="pulse">
        <div class="bar-top"></div>
        <div class="bar-long"></div>
        <div class="bar-bottom"></div>
      </div>
  </div>

  <% if user_signed_in? %>
    <a href="/days" class="option-1 hidden" data-hotdog-navigation-target="option1">progress</a>
    <a href="/days/<%= @day.id %>" class="option-3 hidden" data-hotdog-navigation-target="option2">today</a>
    <%= link_to 'log out', destroy_user_session_path, data: { turbo_method: :delete, hotdog_navigation_target: 'option3' }, class: 'option-2 hidden' %>
  <% else %>
    <a class="option-1 hidden"
      data-login-navigation-target="loginLink"
      data-action="click->login-navigation#openLoginForm">
      log in
    </a>

    <a class="option-2 hidden"
      data-login-navigation-target="signupLink"
      data-action="click->login-navigation#openSignupForm"
      >sign up
    </a>
  <% end %>

  <form action="/user/sign_in" method="post" class="login-form hidden"
        data-login-navigation-target="loginForm"
        data-action="submit->days-generation#loginAndGenerateMissingDays">
    <h1>log in</h1>
    <input type="text" placeholder="Username (required)" name="user[email]" data-days-generation-target="username">
    <input type="password" placeholder="Password (required)" name="user[password]" data-days-generation-target="password">
    <input type="hidden" name="authenticity_token", value="<%= form_authenticity_token %>">
    <input type="submit" value="enter">
  </form>

  <form action="" method="get" class="signup-form hidden"
        data-login-navigation-target="signupForm"
        data-action="submit->days-generation#signupAndGenerateMissingDays">
    <h1>sign up</h1>
    <input type="text" placeholder="Email (required)" data-days-generation-target="emailSignup">
    <input type="password" placeholder="Password (required)" data-days-generation-target="passwordSignup">
    <input type="submit" value="enter">
  </form>

  <div class="bg-circles">
    <div class="one landing"></div>
    <div class="two landing"></div>
    <div class="three landing"></div>
    <div class="four landing"></div>
  </div>
</div>



<div class="landing_container">
  <h1 class="heading">focus.</h1>
  <h2>a fun & simple way <br> to customise your <br>daily tasks.</h2>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>